version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - PORT=${PORT}
    volumes:
      - .:/app
    restart: always
