version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - PORT=${PORT}
    volumes:
      - .:/app
    restart: always